# Generated by Django 4.1.3 on 2022-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0003_ticket_email_ticket_name_ticket_numberofpersons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numberOfPersons',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='watch',
            field=models.TextField(max_length=140),
        ),
    ]
