# Generated by Django 4.1.3 on 2022-12-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0005_ticket_lastname_alter_ticket_date_alter_ticket_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='watch',
            new_name='timee',
        ),
    ]
