# Generated by Django 4.1.3 on 2022-12-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0007_alter_ticket_date_alter_ticket_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lastName',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numberOfPersons',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timee',
            field=models.TextField(max_length=140),
        ),
    ]
