# Generated by Django 4.1.3 on 2022-12-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0011_escaperoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaperoom',
            name='genre',
            field=models.CharField(max_length=30),
        ),
    ]
