# Generated by Django 4.1.3 on 2022-12-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0013_rename_src_escaperoom_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='disableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
