# Generated by Django 4.1.3 on 2022-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0014_disabledate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='idGame',
            field=models.ManyToManyField(to='whatGame.escaperoom'),
        ),
    ]
