# Generated by Django 4.1.3 on 2022-12-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0017_alter_ticket_idgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabledate',
            name='idGame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whatGame.escaperoom'),
            preserve_default=False,
        ),
    ]
