# Generated by Django 4.1.3 on 2023-01-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatGame', '0018_disabledate_idgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaperoom',
            name='priceSans1',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escaperoom',
            name='priceSans2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escaperoom',
            name='priceSans3',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escaperoom',
            name='priceSans4',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escaperoom',
            name='priceSans5',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escaperoom',
            name='priceSans6',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escaperoom',
            name='priceSans7',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
